name: urbangardening
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/profil/
    - images/product/
  fonts:
    - family: Roboto
      fonts: 
        - asset: fonts/Roboto/Roboto-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Regular.ttf